use_frameworks!

platform :ios, '11.0'
workspace 'FoodLensSDKExamples'

examples = ['AICamera', 'SearchFood', 'History', 'LocalHistory', 'RecognizeFood', 'AICameraWithCustomUI', 'ResultFromPictureLibrary', 'AICameraAndViewResult']

abstract_target 'FoodLensExamples' do

    examples.each_with_index { |example, index|
        target example do
            xcodeproj 'Example' + (index + 1).to_s + '_' + example + '/' + example + '.xcodeproj'
        end
    }

    pod 'FoodLensSDK/Static'
end
